server:
  port: 8888
  servlet:
    context-path: /sample

spring:
  application:
    name: sample

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql@Devspace!
    url: jdbc:mysql://10.253.163.195:3306/demo?characterEncoding=utf8&useSSL=false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/**/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1