server:
  port: 8888
  servlet:
    context-path: /sample

spring:
  application:
    name: sample

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql@Devspace!
    url: jdbc:mysql://10.253.160.168:3306/demo?characterEncoding=utf8&useSSL=false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1

liteflow:
#  rule-source: config/flow.el.xml
  rule-source-ext-data-map:
#    url: jdbc:mysql://10.253.160.168:3306/demo?characterEncoding=utf8&useSSL=false
#    driverClassName:  com.mysql.jdbc.Driver
#    username: root
#    password: mysql@Devspace!
    applicationName: demo
    #是否开启SQL日志
    sqlLogEnabled: true
    #是否开启SQL数据轮询自动刷新机制 默认不开启
    pollingEnabled: true
    pollingIntervalSeconds: 60
    pollingStartSeconds: 60
    #以下是chain表的配置，这个一定得有
    chainTableName: chain
    chainApplicationNameField: application_name
    chainNameField: chain_name
    elDataField: el_data
    chainEnableField: enable
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
    scriptTableName: script
    scriptApplicationNameField: application_name
    scriptIdField: script_id
    scriptNameField: script_name
    scriptDataField: script_data
    scriptTypeField: script_type
    scriptLanguageField: language
    scriptEnableField: enable
